services:
  adito:
    environment:
      JVM_XMX: 4G
      SRVCONF_DATABASE: adito
      SRVCONF_DATABASETYP: '12'
      SRVCONF_HOST: mariadb
      SRVCONF_PASSWORD: chamgeme
      SRVCONF_PORT: '3306'
      SRVCONF_SERVER_ID: ''
      SRVCONF_USER: adito
    image: adito/adito
    ports:
    - 7779:7779/tcp
    - 8080:80/tcp
    volumes:
    - /volume/adito/serverlicense.jar:/opt/ADITO/license/serverlicense.jar:ro
#    - /volume/adito/serverconfig.xml:/opt/ADITO/config/serverconfig.xml:ro
    - /volume/adito/ADITOData:/opt/ADITOData:rw
  mariadb:
    command: mysqld --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: adito
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: adito
    image: mariadb:10.1
    volumes:
    - /volume/mariadb:/var/lib/mysql:rw
version: '2.1'
